-- Script per popolare la tabella Libri
-- Data: 30 giugno 2025
-- Autori: Matteo Mantica e Leonardo Lambruschi

INSERT INTO Libri (title, author, year, genre) VALUES
('Il nome della rosa', 'Umberto Eco', '1980', 'Romanzo storico'),
('1984', 'George Orwell', '1949', 'Distopia'),
('Orgoglio e pregiudizio', 'Jane Austen', '1813', 'Romanzo romantico'),
('Il Signore degli Anelli', 'J.R.R. Tolkien', '1954', 'Fantasy'),
('Cime tempestose', 'Emily Brontë', '1847', 'Romanzo gotico'),
('Il giovane Holden', 'J.D. Salinger', '1951', 'Romanzo di formazione'),
('Il grande Gatsby', 'F. Scott Fitzgerald', '1925', 'Romanzo'),
('Moby Dick', 'Herman Melville', '1851', 'Romanzo d''avventura'),
('Anna Karenina', 'Lev Tolstoj', '1877', 'Romanzo'),
('Delitto e castigo', 'Fëdor Dostoevskij', '1866', 'Romanzo psicologico'),
('Cent''anni di solitudine', 'Gabriel García Márquez', '1967', 'Realismo magico'),
('Il Piccolo Principe', 'Antoine de Saint-Exupéry', '1943', 'Favola'),
('Ulisse', 'James Joyce', '1922', 'Romanzo sperimentale'),
('Don Chisciotte della Mancia', 'Miguel de Cervantes', '1605', 'Romanzo cavalleresco'),
('Madame Bovary', 'Gustave Flaubert', '1856', 'Romanzo realista'),
('Guerra e pace', 'Lev Tolstoj', '1869', 'Romanzo storico'),
('Le avventure di Huckleberry Finn', 'Mark Twain', '1884', 'Romanzo d''avventura'),
('Il processo', 'Franz Kafka', '1925', 'Romanzo filosofico'),
('Il vecchio e il mare', 'Ernest Hemingway', '1952', 'Romanzo breve'),
('Lolita', 'Vladimir Nabokov', '1955', 'Romanzo'),
('Il buio oltre la siepe', 'Harper Lee', '1960', 'Romanzo di formazione'),
('Frankenstein', 'Mary Shelley', '1818', 'Romanzo gotico'),
('L''amante di Lady Chatterley', 'D.H. Lawrence', '1928', 'Romanzo erotico'),
('Il ritratto di Dorian Gray', 'Oscar Wilde', '1890', 'Romanzo filosofico'),
('Lo Hobbit', 'J.R.R. Tolkien', '1937', 'Fantasy'),
('Il Conte di Montecristo', 'Alexandre Dumas', '1844', 'Romanzo d''avventura'),
('Jane Eyre', 'Charlotte Brontë', '1847', 'Romanzo gotico'),
('Le cronache di Narnia', 'C.S. Lewis', '1950', 'Fantasy'),
('Il Padrino', 'Mario Puzo', '1969', 'Romanzo criminale'),
('Fahrenheit 451', 'Ray Bradbury', '1953', 'Distopia'),
('Il Gattopardo', 'Giuseppe Tomasi di Lampedusa', '1958', 'Romanzo storico'),
('L''isola del tesoro', 'Robert Louis Stevenson', '1883', 'Romanzo d''avventura'),
('Il fu Mattia Pascal', 'Luigi Pirandello', '1904', 'Romanzo'),
('La metamorfosi', 'Franz Kafka', '1915', 'Racconto'),
('Alla ricerca del tempo perduto', 'Marcel Proust', '1913', 'Romanzo'),
('Il mondo nuovo', 'Aldous Huxley', '1932', 'Distopia'),
('Uno, nessuno e centomila', 'Luigi Pirandello', '1926', 'Romanzo'),
('Addio alle armi', 'Ernest Hemingway', '1929', 'Romanzo di guerra'),
('La nausea', 'Jean-Paul Sartre', '1938', 'Romanzo filosofico'),
('L''amico ritrovato', 'Fred Uhlman', '1971', 'Romanzo breve'),
('Il tamburo di latta', 'Günter Grass', '1959', 'Romanzo'),
('La montagna incantata', 'Thomas Mann', '1924', 'Romanzo filosofico'),
('L''uomo senza qualità', 'Robert Musil', '1930', 'Romanzo'),
('Il dottor Živago', 'Boris Pasternak', '1957', 'Romanzo storico'),
('Cent''anni', 'Günter Grass', '1995', 'Romanzo storico'),
('La casa degli spiriti', 'Isabel Allende', '1982', 'Realismo magico'),
('Il profumo', 'Patrick Süskind', '1985', 'Romanzo storico'),
('L''insostenibile leggerezza dell''essere', 'Milan Kundera', '1984', 'Romanzo filosofico'),
('L''ombra del vento', 'Carlos Ruiz Zafón', '2001', 'Romanzo gotico'),
('Il cacciatore di aquiloni', 'Khaled Hosseini', '2003', 'Romanzo'),
('La solitudine dei numeri primi', 'Paolo Giordano', '2008', 'Romanzo'),
('Il codice da Vinci', 'Dan Brown', '2003', 'Thriller'),
('Le particelle elementari', 'Michel Houellebecq', '1998', 'Romanzo'),
('American Psycho', 'Bret Easton Ellis', '1991', 'Romanzo psicologico'),
('Neuromante', 'William Gibson', '1984', 'Cyberpunk'),
('La versione di Barney', 'Mordecai Richler', '1997', 'Romanzo'),
('Le correzioni', 'Jonathan Franzen', '2001', 'Romanzo'),
('Il dio delle piccole cose', 'Arundhati Roy', '1997', 'Romanzo'),
('L''eleganza del riccio', 'Muriel Barbery', '2006', 'Romanzo filosofico'),
('La ragazza con l''orecchino di perla', 'Tracy Chevalier', '1999', 'Romanzo storico'),
('La strada', 'Cormac McCarthy', '2006', 'Romanzo post-apocalittico'),
('Norwegian Wood', 'Haruki Murakami', '1987', 'Romanzo'),
('L''amica geniale', 'Elena Ferrante', '2011', 'Romanzo'),
('Il signore delle mosche', 'William Golding', '1954', 'Romanzo allegorico'),
('Cronache marziane', 'Ray Bradbury', '1950', 'Fantascienza'),
('Dune', 'Frank Herbert', '1965', 'Fantascienza'),
('Io, robot', 'Isaac Asimov', '1950', 'Fantascienza'),
('La mano sinistra delle tenebre', 'Ursula K. Le Guin', '1969', 'Fantascienza'),
('Guida galattica per gli autostoppisti', 'Douglas Adams', '1979', 'Fantascienza umoristica'),
('Snow Crash', 'Neal Stephenson', '1992', 'Cyberpunk'),
('La macchina del tempo', 'H.G. Wells', '1895', 'Fantascienza'),
('Il maestro e Margherita', 'Michail Bulgakov', '1967', 'Romanzo fantastico'),
('Sulla strada', 'Jack Kerouac', '1957', 'Romanzo'),
('La fattoria degli animali', 'George Orwell', '1945', 'Satira politica'),
('Cuore di tenebra', 'Joseph Conrad', '1899', 'Romanzo breve'),
('I Promessi Sposi', 'Alessandro Manzoni', '1827', 'Romanzo storico'),
('Ragione e sentimento', 'Jane Austen', '1811', 'Romanzo romantico'),
('Il giardino dei Finzi-Contini', 'Giorgio Bassani', '1962', 'Romanzo'),
('La coscienza di Zeno', 'Italo Svevo', '1923', 'Romanzo psicologico'),
('Memorie di Adriano', 'Marguerite Yourcenar', '1951', 'Romanzo storico'),
('Il barone rampante', 'Italo Calvino', '1957', 'Romanzo fantastico'),
('La peste', 'Albert Camus', '1947', 'Romanzo filosofico'),
('Furore', 'John Steinbeck', '1939', 'Romanzo sociale'),
('La luna e i falò', 'Cesare Pavese', '1950', 'Romanzo'),
('Se questo è un uomo', 'Primo Levi', '1947', 'Memorie'),
('Il deserto dei Tartari', 'Dino Buzzati', '1940', 'Romanzo'),
('La Storia', 'Elsa Morante', '1974', 'Romanzo storico'),
('Il giorno della civetta', 'Leonardo Sciascia', '1961', 'Romanzo poliziesco'),
('Il curioso caso di Benjamin Button', 'F. Scott Fitzgerald', '1922', 'Racconto'),
('La vita è altrove', 'Milan Kundera', '1973', 'Romanzo'),
('Il pendolo di Foucault', 'Umberto Eco', '1988', 'Romanzo storico'),
('L''isola di Arturo', 'Elsa Morante', '1957', 'Romanzo di formazione'),
('La tregua', 'Primo Levi', '1963', 'Memorie'),
('Arancia meccanica', 'Anthony Burgess', '1962', 'Distopia'),
('L''uomo nell''alto castello', 'Philip K. Dick', '1962', 'Fantascienza alternativa'),
('Ubik', 'Philip K. Dick', '1969', 'Fantascienza'),
('Il racconto dell''ancella', 'Margaret Atwood', '1985', 'Distopia'),
('Ready Player One', 'Ernest Cline', '2011', 'Fantascienza'),
('Hunger Games', 'Suzanne Collins', '2008', 'Distopia young adult'),
('Divergent', 'Veronica Roth', '2011', 'Distopia young adult'),
('Il labirinto del fauno', 'Guillermo del Toro', '2019', 'Fantasy'),
('American Gods', 'Neil Gaiman', '2001', 'Fantasy urbano'),
('Coraline', 'Neil Gaiman', '2002', 'Fantasy per ragazzi'),
('Il mare infinito', 'Rick Yancey', '2013', 'Fantascienza young adult'),
('La quinta stagione', 'N.K. Jemisin', '2015', 'Fantasy post-apocalittico'),
('Il problema dei tre corpi', 'Liu Cixin', '2008', 'Fantascienza'),
('La ragazza che saltava nel tempo', 'Yasutaka Tsutsui', '1967', 'Fantascienza'),
('L''uccello del malaugurio', 'Haruki Murakami', '1994', 'Realismo magico'),
('Le nebbie di Avalon', 'Marion Zimmer Bradley', '1979', 'Fantasy storico'),
('Il ciclo di Earthsea', 'Ursula K. Le Guin', '1968', 'Fantasy'),
('La ruota del tempo', 'Robert Jordan', '1990', 'Fantasy epico'),
('Le cronache del ghiaccio e del fuoco', 'George R.R. Martin', '1996', 'Fantasy epico'),
('La torre nera', 'Stephen King', '1982', 'Fantasy western'),
('Il nome del vento', 'Patrick Rothfuss', '2007', 'Fantasy epico'),
('La prima legge', 'Joe Abercrombie', '2006', 'Fantasy'),
('Il libro del nuovo sole', 'Gene Wolfe', '1980', 'Fantasy di fantascienza'),
('La spada della verità', 'Terry Goodkind', '1994', 'Fantasy epico'),
('Il ciclo di Shannara', 'Terry Brooks', '1977', 'Fantasy'),
('La saga di Terramare', 'Ursula K. Le Guin', '1968', 'Fantasy'),
('Il ciclo dell''eredità', 'Christopher Paolini', '2003', 'Fantasy young adult'),
('La saga di Percy Jackson', 'Rick Riordan', '2005', 'Fantasy mitologico'),
('Artemis Fowl', 'Eoin Colfer', '2001', 'Fantasy per ragazzi'),
('La bussola d''oro', 'Philip Pullman', '1995', 'Fantasy per ragazzi'),
('Il trono di spade', 'George R.R. Martin', '1996', 'Fantasy epico'),
('L''assassino del re', 'Robin Hobb', '1996', 'Fantasy'),
('Il ciclo di Darkover', 'Marion Zimmer Bradley', '1958', 'Fantasy di fantascienza'),
('La saga di Geralt di Rivia', 'Andrzej Sapkowski', '1993', 'Fantasy'),
('Il ciclo di Dragonlance', 'Margaret Weis e Tracy Hickman', '1984', 'Fantasy'),
('Il Silmarillion', 'J.R.R. Tolkien', '1977', 'Fantasy mitologico'),
('Harry Potter', 'J.K. Rowling', '1997', 'Fantasy per ragazzi'),
('La storia infinita', 'Michael Ende', '1979', 'Fantasy'),
('Il ciclo di Avalon', 'Marion Zimmer Bradley', '1979', 'Fantasy storico'),
('La saga di Elric di Melniboné', 'Michael Moorcock', '1961', 'Fantasy'),
('Il ciclo dei principi demoni', 'Jack Vance', '1964', 'Fantasy di fantascienza'),
('La saga di Belgariad', 'David Eddings', '1982', 'Fantasy epico'),
('Le cronache di Ambra', 'Roger Zelazny', '1970', 'Fantasy'),
('Il ciclo di Lyonesse', 'Jack Vance', '1983', 'Fantasy'),
('La saga di Rigante', 'David Gemmell', '1998', 'Fantasy eroico'),
('Il ciclo di Majipoor', 'Robert Silverberg', '1980', 'Fantasy di fantascienza'),
('La saga dei Confini del Mondo', 'Tad Williams', '1988', 'Fantasy epico'),
('Il ciclo di Malazan', 'Steven Erikson', '1999', 'Fantasy epico'),
('La saga delle Guardiane dei Sogni', 'Anne Bishop', '1998', 'Fantasy'),
('Il ciclo dell''Impero', 'Raymond E. Feist', '1982', 'Fantasy'),
('La saga di Mistborn', 'Brandon Sanderson', '2006', 'Fantasy'),
('Il ciclo di Farseer', 'Robin Hobb', '1995', 'Fantasy'),
('La saga del Mondo Emerso', 'Licia Troisi', '2004', 'Fantasy'),
('Il ciclo di Riftwar', 'Raymond E. Feist', '1982', 'Fantasy'),
('La saga di Outlander', 'Diana Gabaldon', '1991', 'Fantasy storico'),
('Il ciclo di Abhorsen', 'Garth Nix', '1995', 'Fantasy'),
('La saga di Septimus Heap', 'Angie Sage', '2005', 'Fantasy per ragazzi'),
('Il ciclo di Bartimeus', 'Jonathan Stroud', '2003', 'Fantasy per ragazzi'),
('La saga di Eragon', 'Christopher Paolini', '2003', 'Fantasy young adult'),
('Il ciclo di Mondo Disco', 'Terry Pratchett', '1983', 'Fantasy umoristico'),
('La saga di Twilight', 'Stephenie Meyer', '2005', 'Fantasy romantico'),
('Il ciclo di Deltora', 'Emily Rodda', '2000', 'Fantasy per ragazzi'),
('La saga di Shadowhunters', 'Cassandra Clare', '2007', 'Fantasy urbano'),
('Il ciclo di Pendragon', 'D.J. MacHale', '2002', 'Fantasy per ragazzi');